dice/urls.py
from django.conf.urls import url

from . import views

app_name = 'dice'
urlpatterns = [
    url(r'^$', views.home, name='home'),
]

dicey9000web/urls.py
from django.conf.urls import url, include
from django.views.generic import RedirectView
from django.contrib import admin


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/dice/', permanent=True)), # redirects the base url to dice
    url(r'^dice/', include('dice.urls')),
    url(r'^admin/', admin.site.urls),
]

dice/models.py
from django.db import models

import random

class DiceRoll():

    def __init__(self, number_of_dice, dice_type, roll_modifier, explode_value, success_condition):
        self.number_of_dice = number_of_dice
        self.dice_type = dice_type
        self.roll_modifier = roll_modifier
        self.explode_value = explode_value
        self.success_condition = success_condition
        self.successes = 0

    def roll_dice(self):
        if self.number_of_dice != None:
            self.results = [random.randint(1, self.dice_type) for i in range(self.number_of_dice)]
            self.formated_results = ['{}'.format(result) for result in self.results]
            return self.results

    @property
    def total(self):
        if self.roll_modifier != None:
            return sum(self.results) + self.roll_modifier

    def explode_dice(self):
        if self.explode_value != None:
            for i, result in enumerate(self.results):
                if result >= self.explode_value:
                    self.results[i+1:i+1] = [random.randint(1, self.dice_type)]
                    self.formated_results[i+1:i+1] = ['x.{}'.format(self.results[i+1])]
        return self.results

    def success_counter(self, html=False):
        if self.success_condition != None:
            self.successes = 0
            for i, result in enumerate(self.results):
                if result >= self.success_condition:
                    self.successes += 1
                    if html==False:
                        self.formated_results[i] = '**{}**'.format(self.formated_results[i])
                    elif html==True:
                        self.formated_results[i] = '<b>{}</b>'.format(self.formated_results[i])
        return self.successes

    def output(self, html=False):
        success_msg = ''
        if self.success_condition != None:
            if self.successes == 0:
                success_msg = '\nFailure...'
                if html==True:
                    success_msg = '<br>Failure...'
            elif self.successes == 1:
                success_msg = '\n**1** success!'
                if html==True:
                    success_msg = '<br><b>1</b> success!'
            elif self.successes > 1:
                success_msg = '\n**{}** successes!'.format(self.successes)
                if html==True:
                    success_msg = '<br><b>{}</b> successes!'.format(self.successes)
                                    
        if self.roll_modifier != None:
            if self.roll_modifier > 0:
                return ' + '.join(self.formated_results) + ' + {} = {}'.format(self.roll_modifier, self.total) + success_msg
            elif self.roll_modifier < 0:
                return ' + '.join(self.formated_results) + ' + ({}) = {}'.format(self.roll_modifier, self.total) + success_msg
            else:
                return ' + '.join(self.formated_results) + ' = {}'.format(self.total) + success_msg
        else:
            return '  '.join(self.formated_results) + success_msg

dice/forms.py
from django import forms
from django.core.exceptions import ValidationError

class HomeDiceRollForm(forms.Form):
    
    number_of_dice = forms.IntegerField(min_value=1, max_value=100, label='Number of Dice')
    dice_type = forms.IntegerField(min_value=1, label='Dice Type')
    roll_modifier = forms.IntegerField(required = False, label='Roll Modifier')
    explode_value = forms.IntegerField(required = False, min_value=3, label='Explode Value')
    success_condition = forms.IntegerField(required = False, min_value=1, label='Success Condition')
    
    def clean_number_of_dice(self):
        data = self.cleaned_data['number_of_dice']
        return data
            
    def clean_dice_type(self):
        return self.cleaned_data['dice_type']

    def clean_roll_modifier(self):
        return self.cleaned_data['roll_modifier']
        
    def clean_explode_value(self):
        data = self.cleaned_data['explode_value']
        try:
            if self.cleaned_data['dice_type'] and data!= None and data > self.cleaned_data['dice_type']:
                raise ValidationError('Ensure this value is less than or equal to Dice Type')
        except (KeyError):
            pass
        return data

    def clean_success_condition(self):
        data = self.cleaned_data['success_condition']
        try:
            if self.cleaned_data['dice_type'] and data != None and data > self.cleaned_data['dice_type']:
                raise ValidationError('Ensure this value is less than or equal to Dice Type')
        except (KeyError):
            pass
        return data

dice/views.py
from django.shortcuts import render

from .forms import HomeDiceRollForm
from .models import DiceRoll

# def home(request):
#     return render(request, 'dice/home.html')

def home(request):
    if request.method == 'POST':
        form = HomeDiceRollForm(request.POST)
        roll_output = ''
        if form.is_valid():
            number_of_dice = form.clean_number_of_dice()
            dice_type = form.clean_dice_type()
            roll_modifier = form.clean_roll_modifier()
            explode_value = form.clean_explode_value()
            success_condition = form.clean_success_condition()
            roll = DiceRoll(number_of_dice, dice_type, roll_modifier, 
                            explode_value, success_condition)
            roll.roll_dice()
            roll.explode_dice()
            roll.success_counter(html=True)
            roll_output = roll.output(html=True)
        return render(request, 'dice/home.html', {
            'form': form,
            'roll_output': roll_output,
        })
        
            
    else:
        form = HomeDiceRollForm()
        return render(request, 'dice/home.html', {'form': form})
   

dice/templates/dice/home.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Add CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'dice/w3.css' %}">
    <link rel="shortcut icon" href="{% static 'dice/images/favicon.ico' %}">

    <title>dicey9000web</title>
  </head>

  <body class="w3-padding w3-light-grey">

    <header class="w3-container w3-round w3-black w3-card-8 w3-row-padding">
      <h1><a href="{% url 'dice:home' %}" class="w3-text-white w3-hover-text-red"
	     style="text-decoration:none">
	  <span class="w3-col" style="width:60px">
	    <img src="{% static 'dice/images/dice.png' %}" alt="dice" style="width:50px">
	  </span>
	  <span class="w3-rest">dicey9000</span>
      </a></h1>
    </header>

    <section class="w3-panel">
      <p class="w3-large"><strong class="w3-hover-text-red">dicey9000</strong> is a dice roll web app powered by
	<a href="https://www.djangoproject.com/" target="_blank" class="w3-text-red">Django</a>
	that was originally designed as a
	<a href="https://discordapp.com/" target="_blank" class="w3-text-red">Discord</a> bot.
	Check out source code for this page at
	<a href="https://github.com/brmedeiros/dicey9000web" target="_blank" class="w3-text-red">
	  Github.</a></p>
      <hr style="border-top: 1px solid LightGrey; margin-bottom: 0;">
	
    </section>

    <section class="w3-panel">
      <h3 class="w3-text-red">Dice Roller</h3>

      <div class="w3-row-padding">

	<div class="w3-col l3 m6">
	  <form method="post" novalidate>
	    {% csrf_token %}
	    {% load widget_tweaks %}
	    {{ form.non_field_errors }}
	    <div class="w3-row-padding">
	      {% for field in form %}
	      <div class="w3-col w3-margin-bottom">
		{% if field.label == "Roll Modifier" %}
		{{ field|add_class:"w3-input w3-border"|attr:"placeholder:0 for sum of the results" }}
		{% else %}
		{{ field|add_class:"w3-input w3-border" }}
		{% endif %}
		<label class="w3-label w3-text-red"><b>{{ field.label }}</b></label>
		{% for error in field.errors %}
		<span class="w3-text-red w3-tiny"><br>{{ error }}</span>
		{% endfor %}
	      </div>
	      {% endfor %}
	    </div>
	    <input type="submit" value="Roll!" class="w3-btn w3-red w3-ripple w3-margin-left w3-margin-bottom">
	  </form>
	</div>

	<div class="w3-rest w3-panel w3-border w3-leftbar">
	  <h3 class="w3-text-red">Roll Results</h4>
	  <div class="w3-large w3-leftbar w3-pale-red">
	    <p class="w3-margin-left" style="white-space:pre-wrap">{{ roll_output|safe }}</p></div>
	</div>
      </div>
    </section>

    <footer class="w3-panel w3-card-4 w3-padding-tiny w3-round w3-grey w3-text-white">
      dicey9000web &copy 2017 by
      <a href="https://github.com/brmedeiros/" target="_blank" style="text-decoration:none"
	 class="w3-hover-text-red">Bruno Medeiros</a>
    </footer>

  </body>
</html>